import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../components/layout/Navbar";
import Footer from "../components/layout/Footer";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Map</title>
        <meta name="description" content="Generated by ENOC" />
      </Head>
      <Navbar />

      <div
        className="xl:h-screen h-auto bg-no-repeat bg-cover  bg-top "
        style={{
          backgroundImage:
            "url(https://cdn.pixabay.com/photo/2016/11/04/10/12/hospice-1797305_960_720.jpg)",
        }}
      >
        <div className=" grid xl:grid-cols-3 grid-cols-1 h-full backdrop-opacity-10 bg-black/30">
          <div className="xl:col-span-2 grid grid-rows-2   ">
            <div className="flex xl:flex-col xl:items-start  items-center p-4 justify-center xl:h-auto  xl:text-7xl md:text-7xl text-3xl ">
              <div>
              <h1 className="title_text  text-white ">
                BIENVENIDOS A
              </h1>
              <h1 className="title_text  text-white tracking-wide underline decoration-pink-500">
                I EXPERIENCE
              </h1> 
              </div>
              <div className="xl:opacity-0 md:opacity-0 opacity-100">
              <Image
              src="/logo.png"
              alt="Picture of logo i experience"
              width={80}
              height={80}
            />
              </div>
            </div>

            <div className="flex flex-col information_text xl:text-xl md:text-xl text-base h-auto xl:p-4 p-2 text-justify text-white tracking-wider ">
              <p>
                En la necesidad de fomentar la igualdad de oportunidades para
                poder viajar de una manera cómoda, autónoma y segura, se ha
                creado I Experience. <br /> Es un sitio web el cual busca
                proporcionar la búsqueda de hoteles, restaurantes y atracciones
                que sean incluyentes. De esta manera las personas con
                capacidades diferentes pueden encontrar lo mejor para su viaje
                además de poder crear una nueva experiencia, porque..
              </p>
              <p>
                <b className="font-extrabold text-2xl">
                  Todos tenemos derecho de viajar, conocer y disfrutar
                </b>
              </p>
            </div>
          </div>
          <div className="flex justify-center items-center xl:opacity-100 md:opacity-100 opacity-0">
            <Image
              src="/logo.png"
              alt="Picture of the author"
              width={300}
              height={150}
            />
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}
