import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../components/layout/Navbar";

import { Button } from '@mui/material'
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();

  const handleClick = () => {
    router.push({
      pathname: '/MapPage',
      query: { Information: 'Hoteles' },
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Map</title>
        <meta name="description" content="Generated by ENOC" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Button variant="contained" size='medium' onClick={handleClick}>Ver hoteles</Button>

      <h1 className="h-20 text-center text-5xl mt-10 ">Este es el comienzo</h1>
    </div>
  );
}
