import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Map from '../components/Map'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Map</title>
        <meta name="description" content="Generated by ENOC" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Este es el comienzo</h1>
      <Map/>
    </div>
  );
}
