import Map from '../components/MyMap'
import { useRouter } from 'next/router';
import Head from 'next/head';
export default function MapPage() {
  const router = useRouter();

  return (
    <div>
      <Head>
      <title>Iexperience</title>
        <meta name="description" content="Mapa generated by ENOC" />
      </Head>
      <Map TypeMap = {router.query.Information}/>     
    </div>
  )
}
